Repository fabric8io/kubernetes-client, pull requests merged in 2018-08, with the labels that each got.

#1164 Fix #1162: delete RC after fully deleting DC
  CHANGELOG.md
  openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/DeploymentConfigOperationsImpl.java
Labels: changes requested

#1166 Fixes #1165: Null parameter values are now handled properly
  CHANGELOG.md
  kubernetes-tests/pom.xml
  kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/TemplateTest.java
  openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/TemplateOperationsImpl.java
Labels: 3.x, changes requested

#1174 Fix #1172 : Use v1beta1 for CronJob
  CHANGELOG.md
  kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/CronJobOperationsImpl.java
  kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/BackwardsCompatibilityInterceptor.java
  kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/CronJobExample.java
  kubernetes-itests/src/test/java/io/fabric8/kubernetes/CronJobIT.java
  kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/CronJobTest.java
Labels: needs code review

#1170 Fix #1140: Provide User Utilities
  CHANGELOG.md
  kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java
  kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableImpl.java
  kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java
  kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/WatchConnectionManager.java
  kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/WatchHTTPManager.java
  kubernetes-client/src/main/java/io/fabric8/kubernetes/client/internal/SSLUtils.java
  kubernetes-client/src/main/java/io/fabric8/kubernetes/client/osgi/ManagedKubernetesClient.java
  kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/HttpClientUtils.java
  kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/KubernetesResourceUtil.java
  kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/ReplaceValueStream.java
  kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/Utils.java
  kubernetes-client/src/test/java/io/fabric8/kubernetes/client/internal/KubernetesResourceUtilTest.java
  kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/LoadMultipleDocumentsFromFileExample.java
  kubernetes-examples/src/main/java/io/fabric8/openshift/examples/LoadExample.java
Labels: needs code review
