Repository fabric8io/kubernetes-client, pull requests merged in 2019-08, with the labels that each got.

#1690 Endpoints should stay pluralized
  CHANGELOG.md
  kubernetes-server-mock/src/main/java/io/fabric8/kubernetes/client/server/mock/KubernetesAttributesExtractor.java
  kubernetes-server-mock/src/test/java/io/fabric8/kubernetes/client/server/mock/KubernetesAttributesExtractorTest.java
Labels: changelog missing

#1666 Fix #1661: Remove generic parameter from KubernetesResource
  CHANGELOG.md
  kubernetes-model/kubernetes-model/src/main/java/io/fabric8/kubernetes/api/model/KubernetesResource.java
Labels: enhancement

#1687 fix: Fixed URL resolution algorithm
  CHANGELOG.md
  kubernetes-model/kubernetes-model/src/main/java/io/fabric8/openshift/api/model/Template.java
  kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/BuildConfigTest.java
  kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/DeploymentConfigTest.java
  kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/GroupTest.java
  kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/KubernetesOperationTest.java
  kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/OAuthClientTest.java
  kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/OpenshiftRoleBindingTest.java
  kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/OpenshiftRoleTest.java
  kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/ProjectRequestTest.java
  kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/ProjectTest.java
  kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/SecurityContextConstraintsTest.java
  kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/SubjectAccessReviewTest.java
  kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/TemplateTest.java
  kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/UserTest.java
  openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/OpenShiftOperation.java
  openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/ProjectRequestsOperationImpl.java
  openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/SubjectAccessReviewOperationImpl.java
Labels: bug

#1693 feature(config): Introduced kubernetes.disable.autoConfig to disable auto configuration in Config constructor
  CHANGELOG.md
  kubernetes-client/src/main/java/io/fabric8/kubernetes/client/BaseClient.java
  kubernetes-client/src/main/java/io/fabric8/kubernetes/client/Config.java
Labels: enhancement

#1695 chore: minor refactoring to OpenShiftOperation.wrap method
  CHANGELOG.md
  openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/OpenShiftOperation.java
Labels: enhancement

#1569 ResourceQuotaTest added
  CHANGELOG.md
  kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/ResourceQuotaTest.java
  kubernetes-tests/src/test/resources/test-resourcequota-deployment.yml
  kubernetes-tests/src/test/resources/test-resourcequota.yml
Labels: gsoc

#1571 PersistentVolumeClaimExample added
  CHANGELOG.md
  kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/PersistentVolumeClaimExample.java
  kubernetes-examples/src/main/resources/test-pv-pod.yml
  kubernetes-examples/src/main/resources/test-storage.yml
Labels: gsoc

#1582 HorizontalPodAutoscalerTest added
  CHANGELOG.md
  kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/HorizontalPodAutoscalerTest.java
  kubernetes-tests/src/test/resources/test-horizontalpodautoscaler.yml
Labels: changes requested, gsoc
