Repository fabric8io/kubernetes-client, pull requests merged in 2019-01, with the labels that each got.

#1305 Adding files to licence check exclusion list.
  CHANGELOG.md
  pom.xml
Labels: changelog missing

#1286 PodPreset Support
  CHANGELOG.md
  kubernetes-client/src/main/java/io/fabric8/kubernetes/client/DefaultKubernetesClient.java
  kubernetes-client/src/main/java/io/fabric8/kubernetes/client/KubernetesClient.java
  kubernetes-client/src/main/java/io/fabric8/kubernetes/client/SettingsAPIGroupClient.java
  kubernetes-client/src/main/java/io/fabric8/kubernetes/client/SettingsAPIGroupExtensionAdapter.java
  kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/SettingsAPIGroupDSL.java
  kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/PodPresetOperationsImpl.java
  kubernetes-client/src/main/java/io/fabric8/kubernetes/client/osgi/ManagedKubernetesClient.java
  kubernetes-client/src/main/resources/META-INF/services/io.fabric8.kubernetes.client.ExtensionAdapter
  kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/PodPresetExamples.java
  kubernetes-examples/src/main/resources/pod-preset-example.yml
  openshift-client/src/main/java/io/fabric8/openshift/client/DefaultOpenShiftClient.java
  openshift-client/src/main/java/io/fabric8/openshift/client/OpenShiftClient.java
  openshift-client/src/main/java/io/fabric8/openshift/client/osgi/ManagedOpenShiftClient.java
Labels: feature

#1319 Java11
  kubernetes-client/pom.xml
  kubernetes-examples/pom.xml
  kubernetes-model/kubernetes-model-annotator/pom.xml
  kubernetes-model/kubernetes-model/pom.xml
  kubernetes-model/pom.xml
  kubernetes-server-mock/pom.xml
  kubernetes-tests/pom.xml
  openshift-client/pom.xml
  platforms/karaf/itests/pom.xml
  platforms/karaf/itests/src/test/java/io/fabric8/kubernetes/karaf/itests/FeatureInstallationTest.java
  platforms/karaf/itests/src/test/java/io/fabric8/kubernetes/karaf/itests/PropertiesOverrideTest.java
  platforms/karaf/itests/src/test/java/io/fabric8/kubernetes/karaf/itests/ServiceTest.java
  platforms/karaf/pom.xml
  pom.xml
Labels: needs code review
