Repository fabric8io/kubernetes-client, pull requests merged in 2019-03, with the labels that each got.

#1353 Fix #1347: the JSON property is apiVersion, not apiGroupVersion
  README.md
  kubernetes-client/src/main/java/io/fabric8/kubernetes/client/Config.java
  kubernetes-client/src/main/java/io/fabric8/kubernetes/client/CustomResource.java
  kubernetes-client/src/main/java/io/fabric8/kubernetes/client/CustomResourceList.java
  kubernetes-client/src/test/resources/test-kubeconfig
  kubernetes-client/src/test/resources/test-kubeconfig-exec
  kubernetes-client/src/test/resources/test-kubeconfig-exec-win
  kubernetes-client/src/test/resources/token-generator-win.bat
  kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/crds/Dummy.java
  kubernetes-server-mock/src/main/java/io/fabric8/kubernetes/client/server/mock/KubernetesResponseComposer.java
Labels: needs code review

#1425 Preserve labels and fields when using CRD's withResourceVersion()
  CHANGELOG.md
  kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java
  kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/HasMetadataOperation.java
  kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/CustomResourceOperationsImpl.java
Labels: changelog missing

#1349 Fix #1314: Support for EC Private Keys
  CHANGELOG.md
  kubernetes-client/pom.xml
  kubernetes-client/src/main/java/io/fabric8/kubernetes/client/Config.java
  kubernetes-client/src/main/java/io/fabric8/kubernetes/client/internal/CertUtils.java
  kubernetes-client/src/test/java/io/fabric8/kubernetes/client/internal/CertUtilsTest.java
  kubernetes-client/src/test/resources/ssl/fabric8-ec.cert
  kubernetes-client/src/test/resources/ssl/fabric8-ec.key
  kubernetes-server-mock/pom.xml
  kubernetes-tests/pom.xml
  openshift-client/pom.xml
  platforms/karaf/features/src/main/resources/feature.xml
  pom.xml
Labels: changes requested
