Repository fabric8io/kubernetes-client, pull requests merged in 2022-02, with the labels that each got.

#3803 [java-gen] Support storage and served in generated CR version
  java-generator/core/src/main/java/io/fabric8/java/generator/CRGeneratorRunner.java
  java-generator/core/src/main/java/io/fabric8/java/generator/nodes/JCRObject.java
  java-generator/core/src/test/java/io/fabric8/java/generator/GeneratorTest.java
  java-generator/core/src/test/resources/io/fabric8/java/generator/approvals/ApprovalTest.testCrontabCrd.approved.txt
  java-generator/core/src/test/resources/io/fabric8/java/generator/approvals/ApprovalTest.testJokeCrd.approved.txt
  java-generator/core/src/test/resources/io/fabric8/java/generator/approvals/ApprovalTest.testKeycloakCrd.approved.txt
Labels: component/java-generator

#3678 add kubernetes-client example for secret
  kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/SecretExamples.java
Labels: doc

#3718 [chore] bump sundrio to 0.80.1
  extensions/istio/tests/src/test/java/io/fabric8/istio/test/v1beta1/CorsPolicyTest.java
  extensions/knative/model/src/test/java/io/fabric8/knative/ModelTest.java
  extensions/tekton/model-v1beta1/src/test/java/io/fabric8/tekton/ModelTest.java
  extensions/volumesnapshot/examples/src/main/java/io/fabric8/volumesnapshot/examples/CreateVolumeSnapshot.java
  extensions/volumesnapshot/examples/src/main/java/io/fabric8/volumesnapshot/examples/CreateVolumeSnapshotClass.java
  extensions/volumesnapshot/tests/src/test/java/io/fabric8/volumesnapshot/test/crud/VolumeSnapshotTest.java
  kubernetes-itests/src/test/java/io/fabric8/kubernetes/CustomResourceDefinitionIT.java
  kubernetes-itests/src/test/java/io/fabric8/openshift/OpenShiftAuthorizationIT.java
  kubernetes-model-generator/openshift-model-hive/src/test/java/io/fabric8/openshift/api/model/hive/v1/HiveConfigTest.java
  kubernetes-model-generator/openshift-model-installer/src/test/java/io/fabric8/openshift/api/model/installer/v1/InstallConfigTest.java
  kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/CSIDriverTest.java
  kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/CertificateSigningRequestTest.java
  kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/FlowSchemaTest.java
  kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/RuntimeClassTest.java
  kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/TokenReviewTest.java
  kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/V1CertificateSigningRequestTest.java
  kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/V1CustomResourceDefinitionTest.java
  kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/ClusterRoleTest.java
  kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/ImageContentSourcePolicyTest.java
  kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/OAuthClientAuthorizationTest.java
  kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/RoleBindingRestrictionTest.java
  kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/UserOAuthAccessTokenTest.java
  kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/hive/HiveConfigTest.java
  pom.xml
Labels: changelog missing

#3834 fix #3818: adding missing throws to launderThrowable
  CHANGELOG.md
  kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/utils/HttpClientUtils.java
  kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/core/v1/PodOperationsImpl.java
Labels: 5.12.x

#3801 [java-gen] Adding support for basic Javadoc comments generation
  java-generator/core/src/main/java/io/fabric8/java/generator/nodes/AbstractJSONSchema2Pojo.java
  java-generator/core/src/main/java/io/fabric8/java/generator/nodes/JArray.java
  java-generator/core/src/main/java/io/fabric8/java/generator/nodes/JEnum.java
  java-generator/core/src/main/java/io/fabric8/java/generator/nodes/JMap.java
  java-generator/core/src/main/java/io/fabric8/java/generator/nodes/JObject.java
  java-generator/core/src/main/java/io/fabric8/java/generator/nodes/JPrimitive.java
  java-generator/core/src/test/resources/io/fabric8/java/generator/approvals/ApprovalTest.testKeycloakCrd.approved.txt
  java-generator/it/src/it/cert-manager/expected/AuthSpec.java
Labels: component/java-generator
